import type { Metadata } from "next";
import { Petrona } from "next/font/google";
import "./globals.css";
import { TRPCProvider } from "@/trpc/client";

const petrona = Petrona({
  variable: "--font-petrona",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${petrona.variable} antialiased`}
      >
       <TRPCProvider>
          {children}
        </TRPCProvider>
      </body>
    </html>
  );
}
